/* This file has been generated by ox-ui-module generator.
 * Please only apply minor changes (better no changes at all) to this file
 * if you want to be able to run the generator again without much trouble.
 *
 * If you really have to change this file for whatever reason, try to contact
 * the core team and describe your use-case. May be, your changes can be
 * integrated into the templates to be of use for everybody.
 */
'use strict';

module.exports = function (grunt) {

    var _ = require('underscore');

    grunt.config.merge(_.extend({
        checkDependencies: {
            bower: {
                options: {
                    packageManager: 'bower',
                    install: true
                }
            }
        }}, grunt.config('checkDependencies'))
    );

    //FIXME: once https://github.com/mzgol/grunt-check-dependencies/pull/8 gets released, switch to this implementation
    //used, so grunt will exit with an exit code of 0 - this is what our API is supposed to behave like
    grunt.registerTask('force', 'switch force option :on or :off', function () {
        grunt.option('force', this.flags.on && !this.flags.off);
    });

    grunt.registerTask('bower', ['force:on', 'checkDependencies:bower', 'force:off']);
};
